// AUTO GENERATED. DO NOT EDIT THIS FILE.
// VERSION 3.5.0 | Last Modified Time: Thu Oct 19 2023 17:57:39 GMT+0200 (Central European Summer Time)
// Copyright © 2023 Dexcom, Inc. All rights reserved.

import Foundation
import SwiftUI

public enum PolarisDesignTokenElevationType {
    case elevation0
    case elevation1
    case elevation2
    case elevation3
    case elevation4
    case elevation5
    case elevation6
}

public struct PolarisDesignTokenElevation {
    let color: Color
    let alpha: Float
    let x: CGFloat
    let y: CGFloat
    let blur: CGFloat
    let spread: CGFloat
    
    public init(color: Color, alpha: Float, x: CGFloat, y: CGFloat, blur: CGFloat, spread: CGFloat) {
        self.color = color
        self.alpha = alpha
        self.x = x
        self.y = y
        self.blur = blur
        self.spread = spread
    }

    public static let elevation0 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0, x: 0, y: 0, blur: 0, spread: 0)
    public static let elevation1 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0.08, x: 0, y: 2, blur: 8, spread: 0)
    public static let elevation2 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0.08, x: 0, y: 4, blur: 14, spread: 0)
    public static let elevation3 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0.16, x: 0, y: 6, blur: 16, spread: 0)
    public static let elevation4 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0.18, x: 0, y: 8, blur: 18, spread: 0)
    public static let elevation5 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0.18, x: 0, y: 12, blur: 24, spread: 0)
    public static let elevation6 = PolarisDesignTokenElevation(color: .polarisColors.elevation, alpha: 0.2, x: 0, y: 14, blur: 28, spread: 0)
}
