// AUTO GENERATED. DO NOT EDIT THIS FILE.
// VERSION 3.5.0 | Last Modified Time: Thu Oct 19 2023 17:57:39 GMT+0200 (Central European Summer Time)
// Copyright © 2023 Dexcom, Inc. All rights reserved.

public struct DexIcons {
    public static let icons = DexAssetsIcons()
    public static let images = DexAssetsImages()
    public static let logos = DexAssetsLogos()
}

public struct DexAssetsIcons {
    public let controls = DexAssetsIconsControls()
    public let devices = DexAssetsIconsDevices()
    public let egv = DexAssetsIconsEgv()
    public let events = DexAssetsIconsEvents()
    public let misc = DexAssetsIconsMisc()
    public let miscCircle = DexAssetsIconsMiscCircle()
    public let nav = DexAssetsIconsNav()
    public let os = DexAssetsIconsOs()
}

public struct DexAssetsIconsOs {
    public let apple = DexAssetsIconsOsApple()
    public let droid = DexAssetsIconsOsDroid()
}

public struct DexAssetsImages {
    public let devices = DexAssetsImagesDevices()
    public let misc = DexAssetsImagesMisc()
}

public struct DexAssetsLogos {
    public let apple = DexAssetsLogosApple()
    public let dexcom = DexAssetsLogosDexcom()
    public let droid = DexAssetsLogosDroid()
    public let regulatory = DexAssetsLogosRegulatory()
}

public struct DexAssetsIconsControls {
    public let icoArrowCurved = "ico_arrow_curved"
    public let icoArrowCurvedFilled = "ico_arrow_curved_filled"
    public let icoCheck = "ico_check"
    public let icoCheckActive = "ico_check_active"
    public let icoChevronBw = "ico_chevron_bw"
    public let icoChevronDw = "ico_chevron_dw"
    public let icoChevronFw = "ico_chevron_fw"
    public let icoChevronUw = "ico_chevron_uw"
    public let icoInfo = "ico_info"
    public let icoPlayFilled = "ico_play_filled"
    public let icoPlus = "ico_plus"
    public let icoPlusCircle = "ico_plus_circle"
    public let icoPlusCircleFill = "ico_plus_circle_fill"
    public let icoRadioActive = "ico_radio_active"
    public let icoRadioInactive = "ico_radio_inactive"
    public let icoRotate = "ico_rotate"
    public let icoTribarMenu = "ico_tribar_menu"
}

public struct DexAssetsIconsDevices {
    public let icoAndroidPhone = "ico_android_phone"
    public let icoAppleWatch = "ico_apple_watch"
    public let icoConnectedPen = "ico_connected_pen"
    public let icoConnectedPenMissing = "ico_connected_pen_missing"
    public let icoConnectedPenPriming = "ico_connected_pen_priming"
    public let icoG6Transmitter = "ico_g6_transmitter"
    public let icoG7Applicator = "ico_g7_applicator"
    public let icoG7Wearable = "ico_g7_wearable"
    public let icoIphone8 = "ico_iphone8"
    public let icoIphonex = "ico_iphonex"
    public let icoOtherWatch = "ico_other_watch"
    public let icoPump = "ico_pump"
    public let icoReceiver = "ico_receiver"
}

public struct DexAssetsIconsEgv {
    public let icoGlucosearrow = "ico_glucosearrow"
}

public struct DexAssetsIconsEvents {
    public let icoActivity = "ico_activity"
    public let icoActivityFill = "ico_activity_fill"
    public let icoBlood = "ico_blood"
    public let icoBloodClock = "ico_blood_clock"
    public let icoBloodError = "ico_blood_error"
    public let icoBloodFill = "ico_blood_fill"
    public let icoBowl = "ico_bowl"
    public let icoBowlFill = "ico_bowl_fill"
    public let icoCalc = "ico_calc"
    public let icoCalcFill = "ico_calc_fill"
    public let icoCalibrate = "ico_calibrate"
    public let icoCalibrateClock = "ico_calibrate_clock"
    public let icoCalibrateError = "ico_calibrate_error"
    public let icoInbox = "ico_inbox"
    public let icoInsulin = "ico_insulin"
    public let icoInsulinFill = "ico_insulin_fill"
    public let icoNotes = "ico_notes"
    public let icoNotesFill = "ico_notes_fill"
}

public struct DexAssetsIconsMisc {
    public let icoAlert = "ico_alert"
    public let icoAlertFill = "ico_alert_fill"
    public let icoBell = "ico_bell"
    public let icoCalendar = "ico_calendar"
    public let icoChart = "ico_chart"
    public let icoClarityFilled = "ico_clarity_filled"
    public let icoDarkmode = "ico_darkmode"
    public let icoDarkmodeFill = "ico_darkmode_fill"
    public let icoDataShare = "ico_data_share"
    public let icoDocument = "ico_document"
    public let icoErrorDroid = "ico_error_droid"
    public let icoFollowers = "ico_followers"
    public let icoGestureExpand = "ico_gesture_expand"
    public let icoGestureTap = "ico_gesture_tap"
    public let icoInfo = "ico_info"
    public let icoInternet = "ico_internet"
    public let icoLightbulb = "ico_lightbulb"
    public let icoLightmode = "ico_lightmode"
    public let icoNotification = "ico_notification"
    public let icoPhone = "ico_phone"
    public let icoPhoneFill = "ico_phone_fill"
    public let icoPhoneSettings = "ico_phone_settings"
    public let icoQuickglance = "ico_quickglance"
    public let icoSettings = "ico_settings"
    public let icoSpeaker = "ico_speaker"
    public let icoSpeakerSilenced = "ico_speaker_silenced"
    public let icoTargetRange = "ico_target_range"
    public let icoTargetRangeFill = "ico_target_range_fill"
    public let icoTimeInRange = "ico_time_in_range"
    public let icoTrendGraph = "ico_trend_graph"
    public let icoVibrate = "ico_vibrate"
    public let icoWarningCloudFill = "ico_warning_cloud_fill"
    public let icoQuestionMark = "ico_question_mark"
}

public struct DexAssetsIconsMiscCircle {
    public let icoBatteryCircle = "ico_battery_circle"
    public let icoBellCircle = "ico_bell_circle"
    public let icoBluetoothCircle = "ico_bluetooth_circle"
    public let icoBluetoothCircleSlash = "ico_bluetooth_circle_slash"
    public let icoCancelCircle = "ico_cancel_circle"
    public let icoCheckCircle = "ico_check_circle"
    public let icoCheckCircleFill = "ico_check_circle_fill"
    public let icoClockCircle = "ico_clock_circle"
    public let icoLocationCircle = "ico_location_circle"
    public let icoLocationCircleDisabled = "ico_location_circle_disabled"
    public let icoProfileCircle = "ico_profile_circle"
    public let icoProfileCircleFill = "ico_profile_circle_fill"
    public let icoQuestionCircle = "ico_question_circle"
    public let icoSearchCircle = "ico_search_circle"
    public let icoSignalCircleSlash = "ico_signal_circle_slash"
    public let icoWarnCircle = "ico_warn_circle"
    public let icoWarnCircleFill = "ico_warn_circle_fill"
    public let icoWarningCircleTriangle = "ico_warning_circle_triangle"
}

public struct DexAssetsIconsNav {
    public let icoConnection = "ico_connection"
    public let icoConnectionFill = "ico_connection_fill"
    public let icoGlucose = "ico_glucose"
    public let icoGlucoseFill = "ico_glucose_fill"
    public let icoHistory = "ico_history"
    public let icoHistoryFill = "ico_history_fill"
    public let icoProfile = "ico_profile"
    public let icoProfileFill = "ico_profile_fill"
    public let icoReports = "ico_reports"
    public let icoReportsFill = "ico_reports_fill"
    public let icoSettings = "ico_settings"
    public let icoSettingsFill = "ico_settings_fill"
}

public struct DexAssetsIconsOsApple {
    public let icoDotsHorizontal = "ico_ios_dots_horizontal"
}

public struct DexAssetsIconsOsDroid {
    public let icoArrowBw = "ico_arrow_bw"
    public let icoArrowDd = "ico_arrow_dd"
    public let icoArrowDu = "ico_arrow_du"
    public let icoArrowDw = "ico_arrow_dw"
    public let icoArrowFw = "ico_arrow_fw"
    public let icoArrowUw = "ico_arrow_uw"
    public let icoBattery = "ico_battery"
    public let icoCancel = "ico_cancel"
    public let icoClose = "ico_close"
    public let icoDonut = "ico_donut"
    public let icoDotsVertical = "ico_dots_vertical"
    public let icoFingerprint = "ico_fingerprint"
    public let icoHourglass = "ico_hourglass"
    public let icoNotificationImportant = "ico_notification_important"
}

public struct DexAssetsImagesDevices {
    public let imgAndroid = "img_android"
    public let imgAndroidBattery = "img_android_battery"
    public let imgAndroidBluetooth = "img_android_bluetooth"
    public let imgAndroidLocation = "img_android_location"
    public let imgAndroidNobluetooth = "img_android_nobluetooth"
    public let imgAndroidNolocation = "img_android_nolocation"
    public let imgAndroidStatus = "img_android_status"
    public let imgAppleWatch = "img_apple_watch"
    public let imgAppleWatchClockGray = "img_apple_watch_clock_gray"
    public let imgAppleWatchCrossRed = "img_apple_watch_cross_red"
    public let imgAppleWatchPairedGreen = "img_apple_watch_paired_green"
    public let imgAppleWatchSearchGray = "img_apple_watch_search_gray"
    public let imgAppleWatchWarningOrange = "img_apple_watch_warning_orange"
    public let imgConnectedPenLilly = "img_connected_pen_lilly"
    public let imgConnectedPenLillyActiveGreen = "img_connected_pen_lilly_active_green"
    public let imgConnectedPenLillyErrorRed = "img_connected_pen_lilly_error_red"
    public let imgConnectedPenNovo = "img_connected_pen_novo"
    public let imgConnectedPenNovoActiveGreen = "img_connected_pen_novo_active_green"
    public let imgConnectedPenNovoErrorRed = "img_connected_pen_novo_error_red"
    public let imgG6Sensor = "img_g6_sensor"
    public let imgG6SensorStatus = "img_g6_sensor_status"
    public let imgG6Transmitter = "img_g6_transmitter"
    public let imgG6TransmitterStatus = "img_g6_transmitter_status"
    public let imgG7Applicator = "img_g7_applicator"
    public let imgG7Receiver = "img_g7_receiver"
    public let imgG7Wearable = "img_g7_wearable"
    public let imgG7WearableBluetoothCircleSlash = "img_g7_wearable_bluetooth_circle_slash"
    public let imgG7WearableClockGray = "img_g7_wearable_clock_gray"
    public let imgG7WearableClockOrange = "img_g7_wearable_clock_orange"
    public let imgG7WearableSearchGray = "img_g7_wearable_search_gray"
    public let imgG7WearableSignalCircleSlash = "img_g7_wearable_signal_circle_slash"
    public let imgG7WearableSignalGreen = "img_g7_wearable_signal_green"
    public let imgG7WearableWarningOrange = "img_g7_wearable_warning_orange"
    public let imgG7WearableWarningRed = "img_g7_wearable_warning_red"
    public let imgIphone8 = "img_iphone8"
    public let imgIphonex = "img_iphonex"
    public let imgPump = "img_pump"
}

public struct DexAssetsImagesMisc {
    public let imgInsulinFastactingBar = "img_insulin_fastacting_bar"
    public let imgInsulinFastactingSquare = "img_insulin_fastacting_square"
    public let imgInsulinLongactingBar = "img_insulin_longacting_bar"
    public let imgInsulinLongactingSquare = "img_insulin_longacting_square"
    public let imgInsulinMissinginfoSquare = "img_insulin_missinginfo_square"
    public let imgQrCode1 = "img_qr_code_1"
    public let imgQrCode2 = "img_qr_code_2"
    public let imgQrCode3 = "img_qr_code_3"
}

public struct DexAssetsLogosApple {
    public let logBattery = "log_battery"
    public let logHealth = "log_health"
    public let logHourglass = "log_hourglass"
    public let logSiri = "log_siri"
}

public struct DexAssetsLogosDexcom {
    public let logClarity = "log_clarity"
    public let logClarityInverted = "log_clarity_inverted"
    public let logD1 = "log_d1"
    public let logFollow = "log_follow"
    public let logFollowInverted = "log_follow_inverted"
    public let logG7 = "log_g7"
}

public struct DexAssetsLogosDroid {
    public let logGoogleFit = "log_google_fit"
}

public struct DexAssetsLogosRegulatory {
    public let logCe = "log_ce"
    public let logUkca = "log_ukca"
}
